import type { Metadata } from 'next'
import { Inter, Manrope } from 'next/font/google'
import './globals.css'
import Header from '@/components/Header/index'
import Footer from '@/components/Footer'
import { cx } from '../components/utils'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-in',
})
const manrope = Manrope({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-mr',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cx(
          inter.variable,
          manrope.variable,
          'font-mr bg-light dark:bg-black'
        )}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
